version: "3.4"

services:
  mysql:
    image: mysql:8.0
    container_name: quick-connect-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_MAIN}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_CONTAINER_PORT}"

  redis:
    image: redis:alpine
    container_name: quick-connect-redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_CONTAINER_PORT}"

  quick-connect-app:
    container_name: quick-connect-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./internal/config/env/.env
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - redis
    ports:
      - "${PORT}:${PORT}"

volumes:
  mysql_data:
